### ISSUE TITLE
Заменить захардкоженый таймаут событием window.onload

### ISSUE THREAD

**Issue by zhuharev** [iserdmi/afterlag-js#3]
`afterlag` всегда наступает после `window.onload`.
Я сначала думал, что у них одинаковое время срабатывания, однако, лаги бывают и после `window.onload`
Поэтому предлагаю заменить таймаут 100мс на событие `windows.onload`. Так скрипт не будет раньше времени тратить ресурсы браузера.

**Comment by pxlvoid** [comment]
Хорошее предложение, кстати

**Comment by iserdmi** [comment]
Скажем есть на странице одна картинка, которая тянется с сервера, который долго отвечает. Вот уже все загрузилось, а эта картинка еще нет. Событие `onload` ещё не сработало, а лаги уже кончились. Выходит, что нельзя запускать афтерлаг после `onload`, нужно запускать раньше. Или я что-то упускаю?

Задержка в 100мс нужна не для того, чтобы переплюнуть `windows.onload`. По какой-то причине в самом начале браузер уходит в короткое затишье перед бурей, и афтерлаг может успеть решить, что лагов нет и вызвать все колбэки. Звучит дилетантски, и скорее всего у каждого клиента длительность этого затишья скорее индивидуальная. Тут важно понимать, что афтерлаг  не панацея, и работать так как ожидается в 100% случаев не будет. Можно лишь стремиться к идеалу, играясь с настройками. 

В качестве альтернативы параметру настроек `delay`, я собираюсь ввести параметр, который будет принимать булево значение. Если установить его в `true`, то афтерлаг сработает только после того как лаги закончатся. Сейчас афтерлаг вызывает колбэки, если после его запуска сразу было обнаружено, что лагов нету вовсе. При истинности нового параметра, афтерлаг будет ждать появления лагов и только после их окончания вызовет колбэки. Если лаги так и не наступят афтерлаг вызовет колбэки только по истечении времени указанного в параметре настроек `timeout`.

**Comment by zhuharev** [comment]
Потестил в браузере на глазок.
[Изменил немного тестовый файл](https://zhuharev.ru/static/afterlag-js/demo/)
Лаги происходят во время отрисовки новых элементов. Отрисовка больших картинок тоже создаёт лаги, поэтому для меня `window.onload` выглядит более привлекательно. Но. Когда афтерлаг срабатывает до `window.onload`, почти всегда это ложное срабатывание и лаги ещё продолжаются. И по событий `window.onload` тоже происходят лаги, но заметно реже.

Но это всё гадание на кофейной гуще. Я думаю нужно написать тесты и гонять их через [phantomjs](http://phantomjs.org/).

**Comment by zhuharev** [comment]
Хотя на счёт `window.onload` вы правы, если какая-нибудь картинка метрики медленно загружается, то она не будет вызывать лагов при загрузке. Тонкая грань.

**Comment by iserdmi** [comment]
Ваше демо убедительное. Я сейчас хочу набрать достаточное количество обратной связи, чтобы глубже понять проблемы и, возможно, переосмыслить подход к решению задачи. На данный момент, в моём представлении, проблемы должны решиться изменением дефолтных настроек. Сейчас афтерлаг, если не наблюдает лагов в течении 90мс, уже срабатывает. Видимо это очень мало. В частности лаги в вашем демо будут отлично обрабатываться, если я выставлю `frequency = 200`. По крайней мере в моем браузере.

Вот только цифры эти опять с потолка. Я пока не могу понять, чем мотивироваться при установке дефолтных значений, по какой методике действовать.
