### ISSUE TITLE
[IE8] Зарезервированное слово "do"

### ISSUE THREAD

**Issue by lomadurov** [iserdmi/afterlag-js#5]
К сожалению IE8 не поддерживает ECMAScript 5 и запрещает использовать [зарезервированные имена](http://www.w3schools.com/js/js_reserved.asp) в именах свойств. В связи с этим вываливается исключение.

**Comment by iserdmi** [comment]
Понял, спасибо. На днях переименую этот метод.

**Comment by iserdmi** [comment]
Замени метод «do» на метод «run».

**Comment by lomadurov** [comment]
:+1: Спасибо
